/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfrom_lanjutan;

/**
 *
 * @author MSI GF
 */
public class nyoba2 extends javax.swing.JFrame {

    /**
     * Creates new form nyoba2
     */
    public nyoba2(String nama, String absen, String kelas, String jurusan, String alamat) {
       Hasil1.setText(nama);
       Hasil2.setText(absen);
       Hasil3.setText(kelas);
       Hasil4.setText(jurusan);
       Hasil5.setText(alamat);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hasil5 = new javax.swing.JLabel();
        Hasil2 = new javax.swing.JLabel();
        Hasil3 = new javax.swing.JLabel();
        Hasil4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Hasil1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Hasil5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hasil5.setText("HASIL 5");
        getContentPane().add(Hasil5);
        Hasil5.setBounds(60, 340, 58, 17);

        Hasil2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hasil2.setText("HASIL 2");
        getContentPane().add(Hasil2);
        Hasil2.setBounds(60, 160, 58, 17);

        Hasil3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hasil3.setText("HASIL 3");
        getContentPane().add(Hasil3);
        Hasil3.setBounds(60, 220, 58, 17);

        Hasil4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hasil4.setText("HASIL 4");
        getContentPane().add(Hasil4);
        Hasil4.setBounds(60, 280, 58, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HASIL BIODATA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(193, 37, 116, 17);

        Hasil1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hasil1.setText("HASIL 1");
        getContentPane().add(Hasil1);
        Hasil1.setBounds(60, 110, 58, 17);

        setBounds(0, 0, 523, 596);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nyoba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nyoba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nyoba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nyoba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil1;
    private javax.swing.JLabel Hasil2;
    private javax.swing.JLabel Hasil3;
    private javax.swing.JLabel Hasil4;
    private javax.swing.JLabel Hasil5;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
