/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jform;

/**
 *
 * @author MSI GF
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hargabarang2 = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        hargabarang3 = new javax.swing.JTextField();
        hargabarang4 = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        hargabarang1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 130, 50);

        jLabel2.setText("HARGA BARANG 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 160, 110, 30);

        jLabel6.setText("DISKON");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 360, 110, 40);

        hargabarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabarang2ActionPerformed(evt);
            }
        });
        getContentPane().add(hargabarang2);
        hargabarang2.setBounds(170, 160, 260, 40);

        OK.setText("PROSES");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(120, 460, 90, 30);

        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(250, 460, 90, 30);

        exit.setText("KELUAR");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(380, 460, 90, 30);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 520, 450, 170);

        hargabarang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabarang3ActionPerformed(evt);
            }
        });
        getContentPane().add(hargabarang3);
        hargabarang3.setBounds(170, 220, 260, 40);

        hargabarang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabarang4ActionPerformed(evt);
            }
        });
        getContentPane().add(hargabarang4);
        hargabarang4.setBounds(170, 280, 260, 40);

        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });
        getContentPane().add(diskon);
        diskon.setBounds(170, 360, 260, 40);

        hargabarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabarang1ActionPerformed(evt);
            }
        });
        getContentPane().add(hargabarang1);
        hargabarang1.setBounds(170, 100, 260, 40);

        jLabel7.setText("HARGA BARANG 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 220, 110, 30);

        jLabel8.setText("HARGA BARANG 4");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 270, 110, 50);

        jLabel10.setText("HARGA BARANG 1");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 110, 110, 30);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 710);

        setBounds(0, 0, 636, 756);
    }// </editor-fold>//GEN-END:initComponents

    private void hargabarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabarang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabarang2ActionPerformed

    private void hargabarang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabarang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabarang3ActionPerformed

    private void hargabarang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabarang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabarang4ActionPerformed

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonActionPerformed

    private void hargabarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabarang1ActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        int hb1 = Integer.parseInt(hargabarang1.getText());
        int hb2 = Integer.parseInt(hargabarang2.getText());
        int hb3 = Integer.parseInt(hargabarang3.getText());
        int hb4 = Integer.parseInt(hargabarang4.getText());
        int dis = Integer.parseInt(diskon.getText());
        
        int total = hb1+hb2+hb3+hb4;
        
        int dskn = (total * dis/100);
        int akhir = (total - dskn);
        
        TA.setText("Harga barang : "+hb1+"\nHarga barang 2 : "+hb2+"\nHarga barang 3 : "+hb3+"\nHarga barang 4 : "+hb4+"\nDiskon : "+dis+" %"+"\nTotal : "+total+"\nTotal bayar : "+akhir);
    }//GEN-LAST:event_OKActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        TA.setText("");
        hargabarang1.setText("");
        hargabarang2.setText("");
        hargabarang3.setText("");
        hargabarang4.setText("");
        diskon.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton OK;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hargabarang1;
    private javax.swing.JTextField hargabarang2;
    private javax.swing.JTextField hargabarang3;
    private javax.swing.JTextField hargabarang4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
